<!doctype html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?= $title ?: 'Strona' ?> - Aplikacja w SlimFramework</title>
        <meta name="description" content="<?= $metaDescription ?: 'opis strony' ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" type="text/css" href="/assets/vendor/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="/assets/css/app.css">
        
        <script src="/assets/vendor/jquery/dist/jquery.min.js"></script>
        <script src="/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
    </head>
    <body>
        
        <div class="container">
            <?php include 'menu.phtml'; ?>
            
            <?php if ($flashMessage) : ?>
            <div class="alert alert-info">
                <?= $flashMessage ?>
            </div>
            <?php endif; ?>
        
            <?= ${$this->extendKey()} ?>
        </div>

    </body>

    <script src="/assets/js/app.js"></script>
</html>