<!doctype html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?= $title ?: 'Strona' ?> - Aplikacja w SlimFramework</title>
        <meta name="description" content="<?= $metaDescription ?: 'opis strony' ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>

        <?= ${$this->extendKey()} ?>

    </body>
</html>