<div class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Przełącz menu</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->app()->urlFor('main') ?>">Slim+Faker</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="<?= $this->app()->urlFor('main') ?>">Strona główna</a></li>
                <li><a href="<?= $this->app()->urlFor('hello') ?>">Hello!</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Faker <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<?= $this->app()->urlFor('faker') ?>">Lista zapisanych</a></li>
                        <li><a href="<?= $this->app()->urlFor('faker-improved-insert', ['number' => 5]) ?>">Dodaj 5 losowych</a></li>
                        <li><a href="<?= $this->app()->urlFor('faker-improved-insert', ['number' => 10]) ?>">Dodaj 10 losowych</a></li>
                        <li><a href="<?= $this->app()->urlFor('faker-improved-insert', ['number' => 50]) ?>">Dodaj 50 losowych</a></li>
                        <li><a href="<?= $this->app()->urlFor('faker-improved-insert', ['number' => 100]) ?>">Dodaj 100 losowych</a></li>
                        <li><a href="<?= $this->app()->urlFor('faker-improved-insert', ['number' => 250]) ?>">Dodaj 250 losowych</a></li>
                        <li><a href="<?= $this->app()->urlFor('faker-search') ?>">Szukaj</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            </ul>
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</div>