<?php $this->extend('common/layout.phtml') ?>

<div class="row">
    <div class="col-md-12">
        <div class="well">
            
            <?php if ($name) : ?>
            <h1>Hello, <?= $name ?>!</h1>
            <?php else : ?>
            <h1>Hello!</h1>
            <?php endif; ?>

            <p>
                Twoje IP to <strong><?= $ip ?></strong>
            </p>

        </div>
    </div>
</div>
