<h1>Lista</h1>

<table border="1">
    <thead>
        <tr>
            <th>Imię</th>
            <th>Nazwisko</th>
            <th>Miasto</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td><?= $user['user_name'] ?></td>
            <td><?= $user['user_surname'] ?></td>
            <td><?= $user['user_city'] ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<ul>
    <?php if (1 < $page) : ?>
    <li><a href="<?= $pagePrev ?>">Wstecz</li>
    <?php endif; ?>

    <li><?= $page ?></li>

    <li><a href="<?= $pageNext ?>">Dalej</li>
</ul>
    
