<?php $this->extend('common/layout.phtml') ?>

<h1>Lista</h1>

<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>Imię</th>
            <th>Nazwisko</th>
            <th>Miasto</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td><?= $user['user_name'] ?></td>
            <td><?= $user['user_surname'] ?></td>
            <td><?= $user['user_city'] ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<ul class="pagination">
    <?php if (1 < $page) : ?>
    <li><a href="<?= $pagePrev ?>">Wstecz</a></li>
    <?php else: ?>
    <li class="disabled"><a>Wstecz</a></li>
    <?php endif; ?>

    <li class="disabled"><a><?= $page ?></a></li>

    <li><a href="<?= $pageNext ?>">Dalej</a></li>
</ul>
    
